backend/accounts/urls.py
from django.urls import path, include
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    # path('accounts', views.account_list),
    # path('accounts/<int:account_pk>', views.account),
    # path('auth', include('rest_framework.urls', namespace='rest_framework'))
]

backend/home_menu_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/menus/', include('menus.urls')),
    path('api/accounts/', include('accounts.urls')),
]

backend/menus/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'menus', views.MenuIndexView, basename='menus')

app_name = 'menus'
urlpatterns = [
    path('', views.menu_index),
    path('random_menu/', views.random_menu),
    path('menu/<int:menu_id>/', views.menu_detail),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Account(models.Model):
    name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 200)
    password = models.CharField(max_length = 200)
    created_at = models.DateTimeField(auto_now_add=True)

backend/menus/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    score = models.IntegerField()
    image = models.ImageField(blank=True, null=True, upload_to='images')
    category1 = models.CharField(max_length=20)
    category2 = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.title

backend/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        # 현재 django에서 활성화된 User 모델 가져옴
        model = get_user_model()
        # 상속하는 부모 클래스의 Meta class 내 fields, 그리고 내가 원하는 fields 추가
        fields = UserCreationForm.Meta.fields + ('email',)

backend/accounts/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Account
from .serializers import AccountSerializer
from rest_framework.parsers import JSONParser
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        pass
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return render(request, 'accounts/login_success.html')
    
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)
        
        
@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return render(request, 'accounts/logout_success.html')
    else:
        return render(request, 'accounts/already_logged_out.html')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        pass
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return render(request, 'accounts/signup_success.html')
        
    else:
        form = CustomUserCreationForm()
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

# @csrf_exempt
# def account_list(request):
#     # if request.method == 'GET':
#     #     query_set = Account.objects.all()
#     #     serializer = AccountSerializer(query_set, many=True)
#     #     return JsonResponse(serializer.data, safe=False)

#     if request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = AccountSerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return JsonResponse(serializer.data, status=201)
#         return JsonResponse(serializer.errors, status=400)


# @csrf_exempt
# def account(request, account_pk):
#     account = get_object_or_404(Account, pk=account_pk)

#     if request.method == 'GET':
#         serializer = AccountSerializer(account)
#         return JsonResponse(serializer.data, safe=False)

#     elif request.method == 'PUT':
#         data = JSONParser().parse(request)
#         serializer = AccountSerializer(account, data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return JsonResponse(serializer.data, status=201)
#         return JsonResponse(serializer.errors, status=400)

#     elif request.method == 'DELETE':
#         account.delete()
#         return HttpResponse(status=204)


# @csrf_exempt
# def login(request):
#     if request.method == 'POST':
#         data = JSONParser().parse(request)
#         search_email = data['email']
#         obj = Account.objects.get(email=search_email)

#         if data['password'] == obj.password:
#             return HttpResponse(status=200)
#         else:
#             return HttpResponse(status=400)

backend/menus/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
# from rest_framework import generics
from rest_framework.response import Response
from .models import Menu
from .serializers import MenuSerializer, MenuListSerializer
from rest_framework.decorators import api_view
from rest_framework import status, viewsets
import json
from random import random, sample
from django.views.decorators.csrf import ensure_csrf_cookie
    
    
@api_view(['GET', 'POST'])
def menu_index(request):
    if request.method == 'GET':
        order = request.query_params['order']
        ascDesc = int(request.query_params['ascDesc'])
        
        if ascDesc:
            if order[0] == '-':
                order = order[1:]
            else:
                order = '-' + order
        
        menus = Menu.objects.order_by(order)
        if request.method=='GET':
            serializer = MenuListSerializer(menus, many=True)
            return Response(serializer.data)
    
    elif request.method=='POST':
        print('########################')
        data = request.data
        print(data)
        
        menu = {}
        menu['title'] = data['title']
        menu['description'] = data['description']
        menu['score'] = data['score']
        menu['category1'] = data['category1']
        menu['category2'] = data['category2']
        menu['file'] = data['file']
        print(data['file'])
        serializer = MenuSerializer(data=menu)
        if serializer.is_valid():
            serializer.save()
        return Response(data)


@api_view(['GET'])
def random_menu(request):
    menus = get_list_or_404(Menu)
    random_menu = sample(menus, 1)[0]
    serializer = MenuSerializer(random_menu)
    return Response(serializer.data)
    
    
    
class MenuIndexView(viewsets.ModelViewSet):
    serializer_class = MenuSerializer()
    queryset = Menu.objects.order_by('-pk')
    
    
    
@api_view(['GET', 'DELETE'])
def menu_detail(request, menu_id):
    menu = get_object_or_404(Menu, pk=menu_id)
    if request.method == 'GET':
        serializer = MenuSerializer(menu)
        return Response(serializer.data)
    
    elif request.method == 'DELETE':
        menu.delete()
        data = {
            'message': '삭제되었습니다.'
        }
        return JsonResponse(data)

backend/accounts/templates/accounts/already_authenticated.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그인 상태에서는 불가능한 작업입니다.</h1>
  <hr>
  <a href="http://localhost:3000/"> 페이지로 이동</a>
{% endblock content %}

backend/accounts/templates/accounts/already_logged_out.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그아웃 상태에서는 불가능한 작업입니다.</h1>
  <hr>
  <a href="http://localhost:3000/"> 페이지로 이동</a>
{% endblock content %}

backend/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그인</h1>
  <hr>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button>완료</button>
  </form>
  <a href="{% url 'accounts:signup' %}">회원가입</a>
  <a href="http://localhost:3000/">홈으로</a>
{% endblock content %}

backend/accounts/templates/accounts/login_success.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그인 성공!</h1>
  <hr>
  <a href="http://localhost:3000/"> 페이지로 이동</a>
{% endblock content %}

backend/accounts/templates/accounts/logout_success.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그아웃되었습니다.</h1>
  <hr>
  <a href="http://localhost:3000/"> 페이지로 이동</a>
{% endblock content %}

backend/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>회원가입</h1>
  <hr>
  <form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form  form %}
    <button>완료</button>
  </form>
  <a href="{% url 'accounts:login' %}">로그인으로</a>
  <a href="http://localhost:3000/"> 홈으로</a>
{% endblock content %}

backend/accounts/templates/accounts/signup_success.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>회원가입 완료</h1>
  <hr>
  <a href="http://localhost:3000/"> 페이지로 이동</a>
{% endblock content %}

backend/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Home Menu</title>
</head>
<body>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>
</body>
</html>